version: '3'

networks:
  myphp:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes: 
      - ./src:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 7000:80
    networks:
      - myphp

  php:
    image: php:7.2-fpm
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - myphp