version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_laravel
    volumes: 
      - .:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80
    networks:
      - laravel

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    container_name: php_lavarel
    volumes:
      - .:/var/www/html
    user: 1000:1000
    networks:
      - laravel

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'laravel123'
      MYSQL_USER: 'user123'
      MYSQL_PASSWORD: 'password123'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306
    networks:
      - laravel

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - laravel

  composer:
    image: composer
    container_name: composer_lavarel
    restart: 'no'
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: composer install
    networks:
      - laravel

volumes:
  mysql: